#pragma once
#define IDI_MY_APP_ICON         201
// String IDs - langue
#define IDS_APP_TITLE           1
#define IDS_SUBTITLE            2
#define IDS_DROP_HINT           3
// Section labels
#define IDS_SEC_VIDEO           10
#define IDS_SEC_MUSIC           11
#define IDS_SEC_SHORT           12
#define IDS_SEC_QUALITY         13
// Champs
#define IDS_BROWSE              20
#define IDS_CROP_START          21
#define IDS_CROP_END            22
#define IDS_CROP_HINT           23
#define IDS_MUS_WAVE_HINT       26
#define IDS_VOLUME              27
#define IDS_BTN_GO              28
// Combo court
#define IDS_LOOP                30
#define IDS_SILENCE             31
// Statut
#define IDS_READY               40
#define IDS_ENCODING            41
#define IDS_DONE_STATUS         42
#define IDS_ERR_STATUS          43
#define IDS_DONE_MSG            44
#define IDS_DONE_TITLE          45
#define IDS_ERR_TITLE           46
// Erreurs validation
#define IDS_ERR_NO_VIDEO        50
#define IDS_ERR_NO_AUDIO        51
#define IDS_ERR_BAD_AUD_START   52
#define IDS_ERR_BAD_VID_START   53
#define IDS_ERR_VID_ORDER       54
#define IDS_ERR_AUD_ORDER       55
#define IDS_ERR_TITLE_VAL       56
// Durée
#define IDS_DURATION_FMT        60
#define IDS_DUR_UNAVAIL         61
// Presets labels (label + desc)
#define IDS_PRE0_LBL            70
#define IDS_PRE0_DSC            71
#define IDS_PRE1_LBL            72
#define IDS_PRE1_DSC            73
#define IDS_PRE2_LBL            74
#define IDS_PRE2_DSC            75
#define IDS_PRE3_LBL            76
#define IDS_PRE3_DSC            77
#define IDS_PRE4_LBL            78
#define IDS_PRE4_DSC            79
// Waveform
#define IDS_WAVE_LOAD           80
#define IDS_WAVE_UNAVAIL        81
#define IDS_WAVE_ANALYZING      82
// Erreurs d'encodage
#define IDS_ENC_ERR_VIDEO_OPEN_FAILED               100
#define IDS_ENC_ERR_VIDEO_STREAM_SELECT_FAILED      101
#define IDS_ENC_ERR_VIDEO_DECODE_FAILED             102
#define IDS_ENC_ERR_VIDEO_TYPE_READ_FAILED          103
#define IDS_ENC_ERR_VIDEO_DIMENSIONS_INVALID        104
#define IDS_ENC_ERR_AUDIO_OPEN_FAILED               105
#define IDS_ENC_ERR_AUDIO_STREAM_SELECT_FAILED      106
#define IDS_ENC_ERR_AUDIO_FORMAT_FAILED             107
#define IDS_ENC_ERR_AUDIO_SEEK_FAILED               108
#define IDS_ENC_ERR_AUDIO_TYPE_READ_FAILED          109
#define IDS_ENC_ERR_OUTPUT_CREATE_FAILED            110
#define IDS_ENC_ERR_VIDEO_STREAM_ADD_FAILED         111
#define IDS_ENC_ERR_VIDEO_STREAM_TYPE_INCOMPATIBLE  112
#define IDS_ENC_ERR_AUDIO_STREAM_ADD_FAILED         113
#define IDS_ENC_ERR_AUDIO_STREAM_CONFIG_FAILED      114
#define IDS_ENC_ERR_VIDEO_SEEK_FAILED               115
#define IDS_ENC_ERR_SINK_WRITER_BEGIN_FAILED        116
#define IDS_ENC_ERR_SINK_WRITER_FINALIZE_FAILED     117
#define IDS_ENC_ERR_VIDEO_READ_FAILED               118
#define IDS_ENC_ERR_VIDEO_WRITE_FAILED              119
#define IDS_ENC_ERR_AUDIO_READ_FAILED               120
#define IDS_ENC_ERR_AUDIO_WRITE_FAILED              121
#define IDS_ENC_ERR_AUDIO_SILENCE_WRITE_FAILED      122
#define IDS_ENC_ERR_AUDIO_LOOP_RESTART_FAILED       123
#define IDS_ENC_ERR_CANCELLED                       124
#define IDS_ENC_ERR_UNKNOWN                         125
